// Auto-generated by new-day tool. No edit required
// Year 2025

use anyhow::Result;

mod day01;
mod day03;

pub const DAYS: &[(&str, fn() -> Result<()>)] =
    &[("1", day01::solve), ("3", day03::solve)];
